import { Recipe, ProductionPreset, Mixer, UserSettings, MasterIngredient } from '../types';

export const INITIAL_SETTINGS: UserSettings = {
  userId: 'default',
  defaultWeightUnit: 'lb',
  defaultWastePercent: 6,
  decimalPlaces: 2,
  theme: 'light',
  businessName: 'Artisan Bakery Co.',
  categoryPresetMap: {
    Cookies: 'Cookies',
    Bread: 'Base Dough',
    Pies: 'Pie Dough',
    'Pie Dough': 'Pie Dough',
    Shortbread: 'Shortbread',
    Pastries: 'Pie Dough',
    Biscuits: 'Cookies',
    Scones: 'Cookies',
    Cakes: 'All',
    Muffins: 'All',
  },
};

export const SAMPLE_MASTER_INGREDIENTS: MasterIngredient[] = [
  { id: 'mi-1', userId: 'default', name: 'All-Purpose Flour', category: 'Flour', subIngredients: 'Wheat Flour, Niacin, Reduced Iron, Thiamine Mononitrate, Riboflavin, Folic Acid', brand: 'King Arthur', supplier: 'BakeMark', netWeight: 50, netWeightUnit: 'lb', packageType: 'Bag', allergens: 'Wheat, Gluten' },
  { id: 'mi-2', userId: 'default', name: 'Bread Flour', category: 'Flour', subIngredients: 'Unbleached Hard Wheat Flour, Malted Barley Flour, Niacin, Reduced Iron, Thiamine Mononitrate', brand: 'King Arthur', supplier: 'Sysco', netWeight: 50, netWeightUnit: 'lb', packageType: 'Bag', allergens: 'Wheat, Gluten' },
  { id: 'mi-3', userId: 'default', name: 'Pastry Flour', category: 'Flour', subIngredients: 'Soft Wheat Flour', brand: 'Gold Medal', supplier: 'US Foods', netWeight: 50, netWeightUnit: 'lb', packageType: 'Bag', allergens: 'Wheat, Gluten' },
  { id: 'mi-4', userId: 'default', name: 'Whole Wheat Flour', category: 'Flour', subIngredients: '100% Whole Grain Hard Red Wheat', brand: 'Bob\'s Red Mill', supplier: 'BakeMark', netWeight: 25, netWeightUnit: 'lb', packageType: 'Bag', allergens: 'Wheat, Gluten' },
  { id: 'mi-5', userId: 'default', name: 'Granulated Sugar', category: 'Sugar', subIngredients: 'Cane Sugar', brand: 'C&H Sugar', supplier: 'Sysco', netWeight: 50, netWeightUnit: 'lb', packageType: 'Bag', allergens: '' },
  { id: 'mi-6', userId: 'default', name: 'Dark Brown Sugar', category: 'Sugar', subIngredients: 'Cane Sugar, Cane Molasses', brand: 'Domino', supplier: 'Sysco', netWeight: 25, netWeightUnit: 'lb', packageType: 'Box', allergens: '' },
  { id: 'mi-7', userId: 'default', name: 'Unsalted Butter', category: 'Fats & Oils', subIngredients: 'Pasteurized Cream, Natural Flavorings', brand: 'Land O\'Lakes', supplier: 'US Foods', netWeight: 36, netWeightUnit: 'lb', packageType: 'Case', allergens: 'Dairy, Milk' },
  { id: 'mi-8', userId: 'default', name: 'Heavy Cream 36%', category: 'Dairy & Milk', subIngredients: 'Heavy Cream, Milk, Contains less than 0.5% of Mono and Diglycerides, Polysorbate 80, Carrageenan', brand: 'Darigold', supplier: 'US Foods', netWeight: 1, netWeightUnit: 'l', packageType: 'Carton', allergens: 'Dairy, Milk' },
  { id: 'mi-9', userId: 'default', name: 'Whole Milk', category: 'Dairy & Milk', subIngredients: 'Grade A Pasteurized Milk, Vitamin D3', brand: 'Horizon Organic', supplier: 'Sysco', netWeight: 1, netWeightUnit: 'l', packageType: 'Bottle', allergens: 'Dairy, Milk' },
  { id: 'mi-10', userId: 'default', name: 'Large Eggs', category: 'Eggs', subIngredients: 'Fresh Grade A Eggs', brand: 'Vital Farms', supplier: 'Local Distributor', netWeight: 15, netWeightUnit: 'doz', packageType: 'Case', allergens: 'Eggs' },
  { id: 'mi-11', userId: 'default', name: 'Baking Powder', category: 'Leavening', subIngredients: 'Sodium Acid Pyrophosphate, Sodium Bicarbonate, Cornstarch, Monocalcium Phosphate', brand: 'Clabber Girl', supplier: 'BakeMark', netWeight: 10, netWeightUnit: 'lb', packageType: 'Pail / Bucket', allergens: '' },
  { id: 'mi-12', userId: 'default', name: 'Baking Soda', category: 'Leavening', subIngredients: 'Sodium Bicarbonate', brand: 'Arm & Hammer', supplier: 'Sysco', netWeight: 5, netWeightUnit: 'lb', packageType: 'Box', allergens: '' },
  { id: 'mi-13', userId: 'default', name: 'Fine Sea Salt', category: 'Salt & Spices', subIngredients: 'Sea Salt, Yellow Prussiate of Soda', brand: 'Morton', supplier: 'Sysco', netWeight: 25, netWeightUnit: 'lb', packageType: 'Bag', allergens: '' },
  { id: 'mi-14', userId: 'default', name: 'Pure Vanilla Extract', category: 'Flavorings', subIngredients: 'Vanilla Bean Extractives in Water, Alcohol (35%)', brand: 'Nielsen-Massey', supplier: 'BakeMark', netWeight: 1, netWeightUnit: 'l', packageType: 'Bottle', allergens: '' },
  { id: 'mi-15', userId: 'default', name: 'Semisweet Chocolate Chips 60%', category: 'Chocolate', subIngredients: 'Sugar, Chocolate Liquor, Cocoa Butter, Milkfat, Soy Lecithin, Natural Vanilla Extract', brand: 'Callebaut', supplier: 'BakeMark', netWeight: 30, netWeightUnit: 'lb', packageType: 'Case', allergens: 'Dairy, Milk, Soy' },
  { id: 'mi-16', userId: 'default', name: 'Creamy Peanut Butter', category: 'Nut Butters', subIngredients: 'Roasted Peanuts, Sugar, Hydrogenated Vegetable Oil, Salt', brand: 'Jif / Sysco', supplier: 'Sysco', netWeight: 4, netWeightUnit: 'lb', packageType: 'Jar', allergens: 'Peanuts' },
];

export const SAMPLE_RECIPES: Recipe[] = [
  {
    id: 'sample-recipe-peanut-butter-cookies',
    userId: 'default',
    name: 'Bakery Peanut Butter Cookies',
    description: 'Classic bakery-style soft & chewy peanut butter cookies with crosshatch fork marks.',
    category: 'Cookies',
    orderIndex: 0,
    batchYieldQuantity: 80,
    batchYieldUnit: 'cookies',
    defaultWastePercent: 0,
    archived: false,
    ingredients: [
      { id: 'pb1', name: 'All-Purpose Flour', quantity: 2400, unit: 'g', notes: 'King Arthur AP' },
      { id: 'pb2', name: 'Creamy Peanut Butter', quantity: 1928, unit: 'g', notes: '4 lb commercial jars' },
      { id: 'pb3', name: 'Unsalted Butter', quantity: 1200, unit: 'g', notes: 'Room temp butter' },
      { id: 'pb4', name: 'Light Brown Sugar', quantity: 1600, unit: 'g' },
      { id: 'pb5', name: 'Granulated Sugar', quantity: 1400, unit: 'g' },
      { id: 'pb6', name: 'Large Eggs', quantity: 16, unit: 'eggs' },
      { id: 'pb7', name: 'Baking Soda', quantity: 36, unit: 'g' },
      { id: 'pb8', name: 'Baking Powder', quantity: 24, unit: 'g' },
      { id: 'pb9', name: 'Fine Sea Salt', quantity: 30, unit: 'g' },
      { id: 'pb10', name: 'Pure Vanilla Extract', quantity: 60, unit: 'ml', densityGramsPerMl: 1 },
    ],
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: 'sample-recipe-chocolate-chip',
    userId: 'default',
    name: 'Classic Chocolate Chip Cookies',
    description: 'Rich, chewy bakery cookies with chocolate chips and brown sugar balance.',
    category: 'Cookies',
    orderIndex: 1,
    batchYieldQuantity: 100,
    batchYieldUnit: 'cookies',
    defaultWastePercent: 2,
    archived: false,
    ingredients: [
      { id: 'i1', name: 'Bread Flour', quantity: 5, unit: 'kg', notes: 'Unbleached 11.5% protein', wastePercent: 1 },
      { id: 'i2', name: 'Granulated Sugar', quantity: 2.5, unit: 'kg' },
      { id: 'i3', name: 'Dark Brown Sugar', quantity: 2.5, unit: 'kg' },
      { id: 'i4', name: 'Unsalted Butter', quantity: 3, unit: 'kg', notes: 'Softened to 65°F' },
      { id: 'i5', name: 'Large Eggs', quantity: 24, unit: 'eggs' },
      { id: 'i6', name: 'Baking Soda', quantity: 60, unit: 'g' },
      { id: 'i7', name: 'Fine Sea Salt', quantity: 50, unit: 'g' },
      { id: 'i8', name: 'Pure Vanilla Extract', quantity: 120, unit: 'ml', densityGramsPerMl: 1 },
      { id: 'i9', name: 'Semisweet Chocolate Chips 60%', quantity: 4, unit: 'kg', wastePercent: 3, notes: 'Fold in last' },
    ],
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: 'sample-recipe-sourdough',
    userId: 'default',
    name: 'Country Sourdough Loaves',
    description: 'Naturally fermented high-hydration country sourdough bread.',
    category: 'Bread',
    orderIndex: 1,
    batchYieldQuantity: 20,
    batchYieldUnit: 'loaves',
    defaultWastePercent: 1.5,
    archived: false,
    ingredients: [
      { id: 's1', name: 'Unbleached Bread Flour', quantity: 10, unit: 'kg' },
      { id: 's2', name: 'Whole Wheat Flour', quantity: 2, unit: 'kg' },
      { id: 's3', name: 'Filtered Water (78°F)', quantity: 8.4, unit: 'l', densityGramsPerMl: 1, notes: '70% Hydration' },
      { id: 's4', name: 'Active Sourdough Starter', quantity: 2, unit: 'kg', notes: '100% hydration fed starter' },
      { id: 's5', name: 'Fine Sea Salt', quantity: 240, unit: 'g', notes: 'Add during autolyse end' },
    ],
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'sample-recipe-biscuits',
    userId: 'default',
    name: 'Flaky Buttermilk Biscuits',
    description: 'Golden, layered Southern buttermilk biscuits made with chilled European butter.',
    category: 'Biscuits',
    orderIndex: 2,
    batchYieldQuantity: 60,
    batchYieldUnit: 'biscuits',
    defaultWastePercent: 1,
    archived: false,
    ingredients: [
      { id: 'b1', name: 'All-Purpose Flour', quantity: 4, unit: 'kg' },
      { id: 'b2', name: 'Cold Unsalted Butter (Cubed)', quantity: 1.5, unit: 'kg' },
      { id: 'b3', name: 'Cultured Buttermilk', quantity: 2.2, unit: 'l', densityGramsPerMl: 1.03 },
      { id: 'b4', name: 'Baking Powder', quantity: 120, unit: 'g' },
      { id: 'b5', name: 'Baking Soda', quantity: 30, unit: 'g' },
      { id: 'b6', name: 'Fine Sea Salt', quantity: 60, unit: 'g' },
    ],
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'sample-recipe-scones',
    userId: 'default',
    name: 'Blueberry Lemon Scones',
    description: 'Tender cream scones packed with fresh blueberries and lemon zest glaze.',
    category: 'Scones',
    orderIndex: 3,
    batchYieldQuantity: 48,
    batchYieldUnit: 'scones',
    defaultWastePercent: 2,
    archived: false,
    ingredients: [
      { id: 'sc1', name: 'Pastry Flour', quantity: 3.5, unit: 'kg' },
      { id: 'sc2', name: 'Heavy Cream 36%', quantity: 1.8, unit: 'l', densityGramsPerMl: 1 },
      { id: 'sc3', name: 'Unsalted Butter (Chilled)', quantity: 800, unit: 'g' },
      { id: 'sc4', name: 'Granulated Sugar', quantity: 600, unit: 'g' },
      { id: 'sc5', name: 'Fresh Blueberries', quantity: 1.2, unit: 'kg' },
      { id: 'sc6', name: 'Baking Powder', quantity: 100, unit: 'g' },
      { id: 'sc7', name: 'Lemon Zest', quantity: 40, unit: 'g' },
    ],
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'sample-recipe-cinnamon-rolls',
    userId: 'default',
    name: 'Brioche Cinnamon Rolls',
    description: 'Fluffy butter brioche dough filled with cinnamon sugar spread.',
    category: 'Pastries',
    orderIndex: 4,
    batchYieldQuantity: 48,
    batchYieldUnit: 'rolls',
    defaultWastePercent: 0,
    archived: false,
    ingredients: [
      { id: 'c1', name: 'Bread Flour', quantity: 4, unit: 'kg' },
      { id: 'c2', name: 'Whole Milk', quantity: 1.5, unit: 'l', densityGramsPerMl: 1.03 },
      { id: 'c3', name: 'Unsalted Butter', quantity: 600, unit: 'g' },
      { id: 'c4', name: 'Caster Sugar', quantity: 500, unit: 'g' },
      { id: 'c5', name: 'Large Eggs', quantity: 12, unit: 'eggs' },
      { id: 'c6', name: 'Instant Dry Yeast', quantity: 50, unit: 'g' },
      { id: 'c7', name: 'Kosher Salt', quantity: 40, unit: 'g' },
    ],
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
];

export const SAMPLE_PRESETS: ProductionPreset[] = [
  // --- Cookies Category ---
  {
    id: 'preset-4oz-cookie',
    userId: 'default',
    name: '4 oz Jumbo Cookie Case',
    category: 'Cookies',
    finishedWeight: 4,
    weightUnit: 'oz',
    quantityPerUnit: 80,
    unitName: 'case',
    expectedYield: '80 cookies @ 4 oz each',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'preset-2oz-cookie',
    userId: 'default',
    name: '2 oz Standard Cookie Case',
    category: 'Cookies',
    finishedWeight: 2,
    weightUnit: 'oz',
    quantityPerUnit: 140,
    unitName: 'case',
    expectedYield: '140 cookies @ 2 oz each',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'preset-1-5oz-tray',
    userId: 'default',
    name: '1.5 oz Mini Cookie Tray',
    category: 'Cookies',
    finishedWeight: 1.5,
    weightUnit: 'oz',
    quantityPerUnit: 24,
    unitName: 'tray',
    expectedYield: '24 cookies @ 1.5 oz each',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- Pie Dough Category ---
  {
    id: 'preset-9in-single-pie',
    userId: 'default',
    name: '9" Single Crust Pie Shells',
    category: 'Pie Dough',
    finishedWeight: 12,
    weightUnit: 'oz',
    quantityPerUnit: 24,
    unitName: 'case',
    expectedYield: '24 single pie crusts @ 12 oz each',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'preset-9in-double-pie',
    userId: 'default',
    name: '9" Double Crust / Slab Pie Set',
    category: 'Pie Dough',
    finishedWeight: 24,
    weightUnit: 'oz',
    quantityPerUnit: 12,
    unitName: 'case',
    expectedYield: '12 double pie crust sets (top + bottom) @ 24 oz total',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'preset-hand-pie',
    userId: 'default',
    name: 'Hand Pie / Turnover Dough Rounds',
    category: 'Pie Dough',
    finishedWeight: 3.5,
    weightUnit: 'oz',
    quantityPerUnit: 60,
    unitName: 'tray',
    expectedYield: '60 hand pie rounds @ 3.5 oz each',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- Base Dough Category ---
  {
    id: 'preset-800g-loaf',
    userId: 'default',
    name: '800g Sourdough Batard Rack',
    category: 'Base Dough',
    finishedWeight: 800,
    weightUnit: 'g',
    quantityPerUnit: 10,
    unitName: 'rack',
    expectedYield: '10 loaves @ 800g each',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'preset-500g-boule',
    userId: 'default',
    name: '500g Boule Proofing Tray',
    category: 'Base Dough',
    finishedWeight: 500,
    weightUnit: 'g',
    quantityPerUnit: 12,
    unitName: 'tray',
    expectedYield: '12 boules @ 500g each',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'preset-1kg-focaccia',
    userId: 'default',
    name: '1 kg Focaccia Sheet Pan Tub',
    category: 'Base Dough',
    finishedWeight: 1,
    weightUnit: 'kg',
    quantityPerUnit: 6,
    unitName: 'tub',
    expectedYield: '6 sheet pan focaccias @ 1 kg each',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- Shortbread Category ---
  {
    id: 'preset-1-2oz-shortbread',
    userId: 'default',
    name: '1.2 oz Shortbread Finger Tray',
    category: 'Shortbread',
    finishedWeight: 1.2,
    weightUnit: 'oz',
    quantityPerUnit: 30,
    unitName: 'tray',
    expectedYield: '30 shortbread fingers @ 1.2 oz each',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'preset-shortbread-tart',
    userId: 'default',
    name: '8" Shortbread Tart Shell Box',
    category: 'Shortbread',
    finishedWeight: 10,
    weightUnit: 'oz',
    quantityPerUnit: 16,
    unitName: 'box',
    expectedYield: '16 tart shells @ 10 oz each',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'preset-2oz-shortbread-rounds',
    userId: 'default',
    name: '2 oz Scottish Shortbread Rounds',
    category: 'Shortbread',
    finishedWeight: 2,
    weightUnit: 'oz',
    quantityPerUnit: 48,
    unitName: 'case',
    expectedYield: '48 shortbread rounds @ 2 oz each',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SAMPLE_MIXERS: Mixer[] = [
  {
    id: 'mixer-hobart-60',
    userId: 'default',
    name: 'Hobart 60-Qt Commercial Mixer',
    maxWeight: 80,
    weightUnit: 'lb',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mixer-spiral-100',
    userId: 'default',
    name: 'Diosna 100 kg Heavy Spiral Mixer',
    maxWeight: 100,
    weightUnit: 'kg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mixer-tabletop-20',
    userId: 'default',
    name: 'KitchenAid Commercial 20-Qt Tabletop',
    maxWeight: 18,
    weightUnit: 'lb',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
